### PR TITLE
Trim the search query

### PR DESCRIPTION
**Pull request by pau1phi11ips**
Trim the search query to stop duplicate terms in the results when someone adds a space on the end

### CODE REVIEW

**Comment by pau1phi11ips** [comment]
I've actually just added this to functions.php file for the same fix.

```php
add_filter('request', function ($query_vars) {
  if (!is_admin() && !empty($query_vars['s'])) {
      $query_vars['s'] = trim($query_vars['s']);
  }

  return $query_vars;
});
```

**Review by Dan0sz — APPROVED** [review]

**Comment by pau1phi11ips** [comment]
@Dan0sz it might be better add `strtolower` too?
image

**Comment by Dan0sz** [comment]
@metmarkosaric what do you think? Convert all search queries to lowercase?

**Comment by metmarkosaric** [comment]
@Dan0sz i think it's a good idea!

**Comment by Dan0sz** [comment]
@pau1phi11ips Go ahead with that PR then 😁

**Comment by pau1phi11ips** [comment]
Done #230. Cheers.

**Pull request merged**
