### PR TITLE
improve settings page to future proof new settings #26

### LINKED ISSUE #26: improve settings page to future proof new settings
### User Story
As a developer, I want to improve the settings page code so that I can make it future proof by developing a settings API that can create setting fields on the fly with few parameters.

### PR DESCRIPTION
**Pull request by mehul0810**
This PR closes #26 and #11 

### Description
I have worked on a couple of issues as a part of this issue:
- Simplified the admin settings field API and storing of data
- Added support for tracking analytics based on user roles
- improved UI

### Screenshots
CleanShot 2021-09-29 at 01 10 19@2x

### CODE REVIEW

**Comment by metmarkosaric** [comment]
it's looking good @mehul0810, thanks!

**Comment by mehul0810** [comment]
Thanks for the review @metmarkosaric 

I have merged this PR 🎉

**Comment by lumpysimon** [comment]
Do you have an estimated date for the next release? I'd love to exclude editors from tracking, but I see this has been approved for over a year, so I wonder if there's a reason it's not been released?

I've just moved five clients to Plausible from Google, and as they all use the Editor role daily this would be really great to improve the accuracy of their stats.

Thanks :)

**Comment by metmarkosaric** [comment]
@lumpysimon we don't have any estimated date at the moment unfortunately. we're in the final stages of testing the next release but this version is focused on introducing the proxy by default (and removing the custom domain feature) in the plugin. this is a major undertaking that has taken a lot of development time. after this major version is released, we plan to review some of the other new additions such as the ability to exclude editors too so these would make it in the version after next. thanks for your patience and do stay tuned!

**Pull request merged**
