### PR TITLE
Allows middle-click and ctrl+click outbound clicks to properly open as user intended? #15

### LINKED ISSUE #15: Allows middle-click and ctrl+click outbound clicks to properly open as user intended?
There's been this fix to the default outbound link click script so unsure if something needs to be changed in the WordPress plugin implementation too? https://github.com/plausible/analytics/pull/494

### PR DESCRIPTION
**Pull request by mehul0810**
### Description
This PR resolves #15 

I have just updated the script. We will do a thorough testing with the pre-releases.

### CODE REVIEW

**Comment by ukutaht** [comment]
Hmm.. any reason why the outbound link tracking is implemented separately from the official version? Maybe I'm missing something but it seems like you could just add `plausible.outbound-links.js` extension to the script if it's enabled and it should work the same and also get future updates/bug fixes, no?

**Comment by mehul0810** [comment]
@ukutaht I have implemented it separately because the `plausible.outbound-links.js` includes main `plausible` script code along with outbound links code and similarly there are 3-4 links for different purposes. So, it makes it better to just include the part of outbound links and attach it to the main script. I hope this answers your question.

**Comment by ukutaht** [comment]
Sorry I don't understand. Yes, the `plausible.outbound-links.js` includes the main script code as well, that's how it's designed to work. If Plausible users want outbound link tracking, we instruct them to replace their current script with `plausible.outbound-links.js`. The main script and outbound link code is not intended to be used as two separate scripts.

What problem is introduced when the plugin loads `plausible.outbound-links.js` instead of `plausible.js` when the user has enabled outbound link tracking? 

Or the inverse - what's the benefit of duplicating the same code in the WP plugin?

The clear disadvantage is that support and maintenance is more difficult this way. When people have problems with outbound link tracking we won't know if they're running the official code or the plugin code. And when we release any updates like allowing middle clicks, then the WP plugin needs to be updated separately, creating more work for you. If the plugin just used our official outbound link tracking these problems would be avoided.

**Comment by mehul0810** [comment]
@ukutaht Let me playaround with the way you mentioned. I will ask you questions, if required.

**Comment by mehul0810** [comment]
@ukutaht I have improved the code based on your suggestion and the documentation here: https://plausible.io/docs/outbound-link-click-tracking

**Review by ukutaht — APPROVED** [review]

**Comment by ukutaht** [comment]
Looks good to me. Less code to maintain in the plugin and we can expect consistent behaviour between the plugin and installing the script directly according to docs.

In the future it's likely we'll have more script extensions (like tracking form conversions for example) that you can hook into easily to make the plugin more powerful. Thanks for making the changes :)

**Comment by mehul0810** [comment]
Merged this PR as it is reviewed and approved.

**Pull request merged**
