### PR TITLE
Add post row analytics link

### PR DESCRIPTION
**Pull request by EdwardBock**
In relation to #148 . This feature is highly requested by our customers. Would be great to have it.

Thanks for you great work!

### CODE REVIEW

**Comment by Dan0sz** [comment]
Thanks for your PR! I like this. @metmarkosaric Shall we include this in the next release? Small piece of code, but rather effective feature!

**Comment by metmarkosaric** [comment]
we can consider it for sure for one of the upcoming releases! 

so this one adds some stats to the post itself but not to the post list? would be nice to see a screenshot or test how this implementation works as I see some people also ask for the stats to be in the post list itself too. 

and more importantly is this on by default and is there a way to disable/enable it in the settings?

**Comment by EdwardBock** [comment]
Hi there, thank for you quick reaction. It's exactly the opposite @metmarkosaric . This one adds a link to the post list not to the post editor. It is on by default and there is currently no option to disable it. But the links is pretty discreet as it only appears on hover over the posts row.

**Comment by metmarkosaric** [comment]
sounds good @EdwardBock, thanks for the contribution! we'll test it and decide how to proceed.

**Comment by EdwardBock** [comment]
Any news here?

**Comment by Dan0sz** [comment]
Hi @EdwardBock,

Thanks for your suggestion!

2 remarks, before we can publish this:

1. It would be nice to also have the link appear in the pages list, not just posts. (and all custom post types, maybe?)
2. The link shouldn't appear if "Disable menu in toolbar" is enabled or, when Plausible Self-hosted (Community Edition) is used, when the private shared link is not entered.

Once you've added these changes, we can take it up in a next release!

**Comment by Dan0sz** [comment]
Closing this, so we can continue in #212

**Pull request merged**
