### PR TITLE
Added: Tagged Events.js

### PR DESCRIPTION
**Pull request by Dan0sz**
This PR also takes care of the following issues:

Fixed: Outbound Links tracking couldn't be disabled.
Fixed: Upgrade script for future version 1.3.0 would keep running at each pageload.

### CODE REVIEW

**Comment by Dan0sz** [comment]
I've added Tagged Events.

@metmarkosaric Could you verify if [this](https://plausible.io/docs/custom-event-goals) is the correct documentation for this feature?

Also, should the link show "Goal Setup", just like Outbound Link Tracking, or "Documentation", like Hash-Based Routing?

afbeelding

**Comment by Dan0sz** [comment]
Currently, the links are as follows:

Outbound links > https://plausible.io/docs/outbound-link-click-tracking#step-2-create-a-custom-event-goal-in-your-plausible-analytics-account
File downloads > https://plausible.io/docs/file-downloads-tracking#step-2-create-a-custom-event-goal-in-your-plausible-analytics-account
Tagged Events > https://plausible.io/docs/custom-event-goals
Hash-based routing > https://plausible.io/docs/hash-based-routing
IE compatibility > https://plausible.io/docs/script-extensions#scriptcompatjs

I think this is a great way to display it, because it leads people to the relevant (to them) section of the documentation. I suppose we could add a asterisk (*) after the _Goal setup_ links, because now it's not very clear that the note underneath is referring to those options. Also going from this, I suppose I should change the Documentation link after Tagged events to Goal setup.

**Comment by metmarkosaric** [comment]
i'll update the wp post to have a specific wp focused link for each of those

**Comment by Dan0sz** [comment]
Done!

afbeelding

**Pull request merged**
