### PR TITLE
add support for self-hosted plausible analytics script #2

### LINKED ISSUE #2: add support for self-hosted plausible analytics script
## User Story
As a user, I want to connect self-hosted Plausible Analytics script to my WordPress website so that I can use the plugin provided by Plausible.

### PR DESCRIPTION
**Pull request by mehul0810**
This PR resolves #2 

## Working Visuals
**Admin settings**
CleanShot 2020-11-26 at 11 39 30

@metmarkosaric Can you check the description part of the Self Hosted Analytics settings in the above GIF file and let me know if there are any improvements?

### CODE REVIEW

**Comment by metmarkosaric** [comment]
Thanks Mehul! How about this for the copy?

Self-hosting Plausible?

If you're self-hosting Plausible on your own infrastructure, enter the domain name to enable the integration with your self-hosted installation. Learn more [about Plausible Self-Hosted](https://plausible.io/self-hosted-web-analytics).

I was thinking is it possible to move the self-hosted setting somewhere less prominent? Perhaps it only shows up after a user clicks "self-hosting Plausible" or something along those lines. This is in order not to cause any confusion with the cloud version. Most of our users are cloud users and the difference between hosted and self-hosted causes confusion to some, so best to have the self-hosted setting somewhere a bit out of the way/less prominent. Self-hosters would know where to find it. Thanks again!

**Comment by mehul0810** [comment]
@metmarkosaric Thanks for your input. Here are the below improvements which I will do:

> Self-hosting Plausible?

Minor change **Self-hosted Plausible?**

> If you're self-hosting Plausible on your own infrastructure, enter the domain name where you installed it to enable the integration with your self-hosted instance. Learn more about Plausible Self-Hosted.

This looks good to me.

> I was thinking is it possible to move the self-hosted setting somewhere less prominent? Perhaps it only shows up after a user clicks "self-hosting Plausible" or something along those lines. This is in order not to cause any confusion with the cloud version. Most of our users are cloud users and the difference between hosted and self-hosted causes confusion to some, so best to have the self-hosted setting somewhere a bit out of the way/less prominent. Self-hosters would know where to find it. 

**In this case, I can have 2 tabs:** 
1. General
2. Advanced (This is where the self-hosted plausible setting will move and any future advanced settings will move here as well)

Let me know if you have any more suggestions

**Comment by metmarkosaric** [comment]
Self-hosted Plausible sounds great! Perhaps the tab can be called "Self-Hosted" as I'm not sure we have much else to put in there at this moment.

**Comment by mehul0810** [comment]
@metmarkosaric I have updated this PR with the below updates:

1. General Tab
image

2. Self Hosted Tab
image

Feel free to merge this PR, if everything in the screenshot looks good to you.

**Comment by metmarkosaric** [comment]
looks great Mehul, thanks!

**Pull request merged**
